receivers: 
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors: 
  memory_limiter:
    check_interval: 1s
    limit_mib: 2000
  batch:

exporters:
  debug:
    verbosity: detailed 
  otlp/elastic: 
    endpoint: 192.168.2.124:8200
    tls:
      insecure: false
      insecure_skip_verify: true
      ca_file: /ca.crt
    headers:
      Authorization: "Bearer secret"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp/elastic]
    metrics:
      receivers: [otlp]
      exporters: [debug, otlp/elastic]
    logs: 
      receivers: [otlp]
      exporters: [debug, otlp/elastic]
